export const authConstants = {
  LOGIN_REQUEST: 'LOGIN_REQUEST',
  LOGIN_FAILURE: 'LOGIN-FAILURE',
  LOGIN_SUCCESS: 'LOGIN_SUCCESS',
  LOGOUT_REQUEST: 'LOGOUT_REQUEST',
  LOGOUT_SUCCESS: 'LOGOUT_SUCCESS',
  LOGOUT_FAILURE: 'LOGOUT_FAILURE',
}

export const userConstants = {
  USER_REGISTER_REQUEST: 'USER_REGISTER_REQUEST',
  USER_REGISTER_SUCCESS: 'USER_REGISTER_SUCCESS',
  USER_REGISTER_FAILURE: 'USER_REGISTER_FAILURE',
  USER_PROFILEUPDATE_REQUEST: 'USER_PROFILEUPDATE_REQUEST',
  USER_PROFILEUPDATE_SUCCESS: 'USER_PROFILEUPDATE_SUCCESS',
  USER_PROFILEUPDATE_FAILURE: 'USER_PROFILEUPDATE_FAILURE',
}

export const loadingConstants = {
  LOADING_STARTED: 'LOADING_STARTED',
  LOADING_FINISHED: 'LOADING_FINISHED',
}
